name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET core SDK
      uses: actions/setup-dotnet@v1.8.1
    - name: Restore dependencies
      run: dotnet restore src/AsyncComponents/
    - name: Build
      run: dotnet build --no-restore src/AsyncComponents/
    - name: Test
      run: dotnet test --no-build --verbosity normal src/AsyncComponents/
